FROM golang:1.26

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ cmd/
COPY internal/ internal/

RUN go build -buildvcs=false -o /server ./cmd/server

CMD ["/server", "--config-dir", "/app/config"]
