services:
  app:
    container_name: dvb-made-easy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7331:7331"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config:/app/config
      - staging:/staging
    group_add:
      - "${DOCKER_GID:-982}"
    security_opt:
      - label:disable

volumes:
  config:
  staging:
    name: dvb-restore-staging
